### ISSUE TITLE
Folder docelowy Docs, główny katalog repozytorium

### ISSUE THREAD

**Issue by martab0** [DocWizard/GHPages-howto#1]
"Uwaga - w tym przypadku folder docelowy musi nazywać się 'Docs' i być w głównym katalogu repozytorium. Czyli jeśli repozytorium mamy w folderze C:\Github\Repozytorium, to folder docelowy ustawiamy jako C:\Github\Repozytorium\Docs."

1) Folder musi nazywać się 'Docs' czy 'docs'? Dalej przy publikowaniu GitHub Pages odnosisz się do 'docs'
2) Folder docelowu musi być w głównym katalogu repozytorium, a jednocześnie projektu Flare - zastanawiam się, jak to lepiej sformułować, żeby było jasne, że w tym przypadku (po zrobieniu bindingu) repozytorium to to samo co projekt Flare...?

**Comment by DocWizard** [comment]
1. Chodzi Ci o [ten screen](https://github.com/DocWizard/GHPages-howto/blob/main/Resources/0.png), czy gdzieś jeszcze to widzisz? 
2. Coś w ten deseń myślę, że wystarczy: 6a3e644a62926dffa18768458851aea3d59da8e9

**Comment by martab0** [comment]
1. Tak, o ten :)
2. Idealnie!!!

**Comment by DocWizard** [comment]
To jest ten jeden przypadek, gdzie nie ma różnicy czy piszemy wielką czy małą literą - przede wszystkim musimy pilnować tego przy ustawianiu Actions. Tak czy siak, dodałem małe wyjaśnienie, i myślę że to wystarczy: 3fe8a1690a4c3d0f904d6b65a2eff0f1119fad9c

Dzięki za feedback!
